name: "CD"
on:
  push:
    branches: ["main"]
jobs:
  cd:
    name: "CD"
    runs-on: ubuntu-latest
    steps:
      - name:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: ./package
        working-directory: functions/rss-to-s3
      # - uses: hashicorp/setup-terraform@v1
      # - run: terraform init
      # - run: terraform fmt -check
      # - run: terraform plan
      # - run: terraform apply -auto-approve
