name: CD
on:
  push:
    branches: ["main"]
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ap-southeast-2
  AWS_REGION: ap-southeast-2
jobs:
  cd:
    name: CD
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - uses: hashicorp/setup-terraform@v1
        with:
          # The terraform_wrapper default (true) breaks everything somehow
          terraform_wrapper: false
      - run: ./lint
      - run: ./build
      - run: ./deploy
      - run: ./test
